#true为开启，false为关闭
#涩涩图片功能的开启或关闭（布尔值）
esese: false

#自动更新功能的开启或关闭（布尔值）
autoUpdate: true

#邮件配置
mailConfig:
  #是否开启邮件功能（布尔值）
  isOpen: false
  #发件人邮箱（字符串）
  from: ""
  #发件人邮箱密码（字符串）
  password: ""
  #收件人邮箱（字符串）
  to: ""
  #邮件服务器地址（字符串）
  host: ""
  #邮件服务器端口（数字）
  port: 465
  #加密类型（字符串）（ssl/tls）
  secure: "ssl"